services:
  php:
    image: php:fpm-bullseye
    volumes_from:
      - data
    networks:
      - backend
    command: ["bash", "-c", "docker-php-ext-install pdo pdo_mysql; php-fpm"]
  web:
    build: .
    restart: unless-stopped
    networks:
      - default
      - backend
    volumes_from:
      - data
    ports:
      - "9000:80"
    depends_on:
      - data
      - php
      - db
  db:
    image: mariadb:latest
    restart: unless-stopped
    networks:
      - backend
    env_file:
      - ./.env
    volumes:
      - ./db:/var/lib/mysql
  data:
    image: busybox
    volumes:
      - ./chyrp:/var/www/html

networks:
  backend:
    internal: true
  default:
